"""Core utilities for Learning to Reset."""

from learning_to_reset.context_manager import (
    ManagedGeneration,
    build_initial_prompt,
    build_retry_prompt,
    extract_answer_text,
    manage_single_clean_cycle,
    response_requests_clean_retry,
)
from learning_to_reset.countdown_solver import CountdownExpression, solve_countdown
from learning_to_reset.countdown_verifier import (
    VerificationResult,
    extract_answer_expression,
    score_countdown_response,
    verify_countdown_expression,
)
from learning_to_reset.data import CountdownSample, TraceRecord, load_countdown_samples, load_trace_records
from learning_to_reset.dataset_prep import (
    export_prepared_datasets,
    prepare_countdown_split,
    prepare_trace_split,
    serialize_prompt_example,
    write_prompt_examples_jsonl,
)
from learning_to_reset.demo import DemoSnapshot, build_demo_report, build_demo_snapshot
from learning_to_reset.eval_runtime import (
    build_countdown_sample_from_example,
    evaluate_countdown_outputs,
    generate_countdown_responses,
    write_evaluation_outputs,
)
from learning_to_reset.model_resolver import default_hf_cache_root, resolve_model_name_or_path
from learning_to_reset.paper_dataset_prep import export_paper_prepared_datasets
from learning_to_reset.paper_sources import (
    DEFAULT_COUNTDOWN_EVAL_DATASET_ID,
    DEFAULT_COUNTDOWN_TRAIN_DATASET_ID,
    DEFAULT_REFERENCE_TRACE_DATASET_ID,
    DEFAULT_TARGET_MODEL_ID,
    DEFAULT_TRACE_SOURCE_MODEL_ID,
    expand_countdown_hf_row,
    extract_behavior_question,
    fetch_countdown_source_records,
    parse_countdown_user_prompt,
    write_jsonl_records,
)
from learning_to_reset.pipeline import (
    DatasetSplit,
    PromptBatch,
    batch_prompt_examples,
    prepare_countdown_examples,
    prepare_sft_examples,
    split_sequence,
)
from learning_to_reset.prompts import (
    PromptExample,
    ReasoningPromptParts,
    build_countdown_prompt,
    build_reasoning_prompt,
    build_sft_training_example,
    parse_reasoning_prompt,
)
from learning_to_reset.rloo import (
    ModifiedRLOOResult,
    TrajectorySample,
    TrajectoryTerm,
    compute_leave_one_out_advantages,
    compute_modified_rloo_terms,
    compute_total_reward,
)
from learning_to_reset.rloo_runtime import (
    RolloutCandidate,
    RolloutSegment,
    build_policy_trajectory_sample,
    build_rollout_candidate,
    compute_policy_loss,
    evaluate_reset_aware_model,
    evaluate_rollout_candidates,
    rollout_countdown_example,
    summarize_rollout_candidates,
    train_rloo,
)
from learning_to_reset.rollout_runtime import (
    CleanTrajectory,
    RewardBreakdown,
    build_clean_trajectory,
    compute_countdown_reward,
)
from learning_to_reset.sft_runtime import (
    PromptCollator,
    load_prepared_examples,
    render_training_text,
    tokenize_training_example,
    train_sft,
)
from learning_to_reset.synthetic_countdown_traces import (
    build_negative_expression,
    build_negative_trace_record,
    build_positive_trace_record,
    build_synthetic_trace_records,
    generate_synthetic_trace_corpus,
)
from learning_to_reset.trace_bootstrap import (
    build_bootstrap_negative_record,
    build_bootstrap_trace_corpus,
    write_bootstrap_trace_corpus,
)
from learning_to_reset.trace_generation import build_trace_record_from_response, generate_trace_records
from learning_to_reset.trace_curation import (
    CuratedTrace,
    NormalizedTrace,
    curate_trace,
    normalize_trace,
)

__all__ = [
    "CuratedTrace",
    "CountdownSample",
    "CountdownExpression",
    "CleanTrajectory",
    "DEFAULT_COUNTDOWN_EVAL_DATASET_ID",
    "DEFAULT_COUNTDOWN_TRAIN_DATASET_ID",
    "DEFAULT_REFERENCE_TRACE_DATASET_ID",
    "DEFAULT_TARGET_MODEL_ID",
    "DEFAULT_TRACE_SOURCE_MODEL_ID",
    "DatasetSplit",
    "DemoSnapshot",
    "VerificationResult",
    "RewardBreakdown",
    "default_hf_cache_root",
    "build_countdown_sample_from_example",
    "build_bootstrap_negative_record",
    "build_bootstrap_trace_corpus",
    "build_clean_trajectory",
    "build_negative_expression",
    "build_negative_trace_record",
    "build_positive_trace_record",
    "build_synthetic_trace_records",
    "evaluate_countdown_outputs",
    "expand_countdown_hf_row",
    "export_prepared_datasets",
    "export_paper_prepared_datasets",
    "extract_behavior_question",
    "generate_countdown_responses",
    "generate_trace_records",
    "ManagedGeneration",
    "ModifiedRLOOResult",
    "NormalizedTrace",
    "PromptBatch",
    "PromptCollator",
    "PromptExample",
    "ReasoningPromptParts",
    "RolloutCandidate",
    "RolloutSegment",
    "TraceRecord",
    "TrajectorySample",
    "TrajectoryTerm",
    "batch_prompt_examples",
    "build_countdown_prompt",
    "build_initial_prompt",
    "build_retry_prompt",
    "build_demo_report",
    "build_demo_snapshot",
    "build_policy_trajectory_sample",
    "build_reasoning_prompt",
    "build_rollout_candidate",
    "build_sft_training_example",
    "compute_leave_one_out_advantages",
    "compute_modified_rloo_terms",
    "compute_policy_loss",
    "compute_total_reward",
    "compute_countdown_reward",
    "curate_trace",
    "evaluate_reset_aware_model",
    "evaluate_rollout_candidates",
    "fetch_countdown_source_records",
    "extract_answer_expression",
    "extract_answer_text",
    "load_countdown_samples",
    "load_trace_records",
    "load_prepared_examples",
    "manage_single_clean_cycle",
    "normalize_trace",
    "parse_countdown_user_prompt",
    "parse_reasoning_prompt",
    "prepare_countdown_examples",
    "prepare_countdown_split",
    "prepare_sft_examples",
    "prepare_trace_split",
    "resolve_model_name_or_path",
    "response_requests_clean_retry",
    "rollout_countdown_example",
    "score_countdown_response",
    "serialize_prompt_example",
    "solve_countdown",
    "split_sequence",
    "summarize_rollout_candidates",
    "build_trace_record_from_response",
    "render_training_text",
    "tokenize_training_example",
    "train_rloo",
    "train_sft",
    "verify_countdown_expression",
    "write_evaluation_outputs",
    "write_bootstrap_trace_corpus",
    "generate_synthetic_trace_corpus",
    "write_jsonl_records",
    "write_prompt_examples_jsonl",
]
